
name: traefik-ryanjyoder
version: "v1.7.0-rc5"
summary: The Cloud Native Edge Router
description: |
        Træfik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy. Træfik integrates with your existing infrastructure components (Docker, Swarm mode, Kubernetes, Marathon, Consul, Etcd, Rancher, Amazon ECS, ...) and configures itself automatically and dynamically. Pointing Træfik at your orchestrator should be the only configuration step you need.
grade: stable
confinement: strict

apps:
  kiwix-serve:
    command: kiwix-serve
    plugs: [network-bind,removable-media]
  kiwix-manage:
    command: kiwix-manage
  kiwix-read:
    command: kiwix-read
  kiwix-search:
    command: kiwix-search

parts:
  kiwix-tools:
    plugin: dump
    src: kiwix-tools.tar.gz
    override-pull: |
            case "$SNAPCRAFT_ARCH_TRIPLET" in
                i386-linux-gnu)
                        echo i386
                        curl -o kiwix-tools.tar.gz https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-i586-0.6.1-1.tar.gz
                        ;;
                x86_64-linux-gnu)
                        echo x86_64
                        curl -o kiwix-tools.tar.gz https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-0.6.1-1.tar.gz
                        ;;
                arm-linux-gnueabihf)
                        echo arm
                        curl -o kiwix-tools.tar.gz https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf-0.6.1-1.tar.gz
                        ;;
                *)
                        echo "Arch type unknown: $SNAPCRAFT_ARCH_TRIPLET"
                        exit 1
            esac





